### ISSUE TITLE
Server pack support

### ISSUE THREAD

**Issue by Nekroido** [dries007/curseMeta#16]
It would be really nice to have a way to get server version of a modpack (imagine a self-updating modded server). Right now the API lists only client-version files.

Just my thoughts: AddonFile model has IsCompatibleWithClient property. Could be the thing.

**Comment by dries007** [comment]
I just pas on the Curse api values. I don't change them (except for comparability reasons, such as MultiMC).
The server packs are not accessible via the Curse API as far as I know. (They are not visible via the cient I heard, so it makes sense.) If you know different, feel free to let me know! I would love to have support for them.

_Also:_ Nowadays mods indicate client/server side only status in their jar files, so Forge/FML only load them if appropriate. If you install a mod on the server and it crashes, please for the love of everyone else using it, complain to the mod author :smile: . This has been available in some form of another (in Forge and/or FML) since _before 1.7.10_ so their is no excuse to crash a server anymore.

**Comment by Nekroido** [comment]
Most popular mods do have "Download Server Pack" button next to "Install" in Twitch Client, that's why I thought it's possible to get server files too. Anyway, I tried running mods from manifest.json (why abandon a good script if it's working, eh?) and everything seemed to be working just fine, so I might just go with that.
I had problems with client mods till 1.8.9, but never complained to authors though. Good point. 😀
