### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Shnupbups** [dries007/curseMeta#17]
[The staging site and the API](https://staging_cursemeta.dries007.net/) are currently returning an 'Internal Server Error', or Error 500.

**Comment by StarkRG** [comment]
This is still a problem.

**Comment by dries007** [comment]
The staging enviroment is a testing ground for direct access to the API. Since you can now access the API directly from Curse without authentication tokens, I'm moving away from providing this Man-In-The-Middle service. 
When I'm done with my thesis and exams there will be more info on how/what CurseMeta will be.
In the meantime: https://twitchappapi.docs.apiary.io/#
