### ISSUE TITLE
Some pages are returning invalid json

### ISSUE THREAD

**Issue by qurben** [dries007/curseMeta#7]
The following pages return a stacktrace on top of a json error.

- https://cursemeta.dries007.net/228525/2534543.json
- https://cursemeta.dries007.net/281791/2534481.json

See also https://paste.ee/p/zjuT9 for the full error.

**Comment by dries007** [comment]
I hotpatched something together, which should maybe hold up for now, idk.

**Comment by qurben** [comment]
The pages linked here now return proper JSON, but it is of a different schema than the rest of the pages. The elements don't start with a capital letter where in most pages they do.

MultiMC starts complaining about missing children.

**Comment by dries007** [comment]
Oh I forgot about that. It's now fetching from NikkyAI's host, because it seems to be unaffected by this issue.
I'll see if I can path the real version, but I have no ETA.

**Comment by dries007** [comment]
OK, more monkeypatching later, and now the json has uppercase first letters again, hopefully fixing the current issue for now.

By no means is this fix to be considered reliable, but it should hold over until I can try and fix it proper.

**Comment by qurben** [comment]
Awesome! I can confirm that it works now.

**Comment by dries007** [comment]
Quick update: For now the service will continue to be a patched together mess of crap, but I've uncovered the secrets deep within the Twitch launcher to find how to fix everything.

It will require a full re-write of CurseMeta as it currently exists, so it will take a while.
In the meantime I intend to patch the C# code to eat a token from a file and periodically refreshing that, so we can at least keep going for now.

**This will affect the reliability of CurseMeta for now** because there won't be any proper error checking, and I can't implement the C# fix until I have some time, hopefully tomorrow.

**Comment by dries007** [comment]
See #9
